package continuity

import (
	"context"
	"errors"
)

var ErrHostCapabilityUnavailable = errors.New("continuity host capability unavailable")
var ErrHostPreparationMissing = errors.New("continuity host has no prepared successor")

type HostCapabilities struct {
	ContextTelemetry       bool
	IdempotentPrepare      bool
	IdempotentActivate     bool
	SuccessorActivation    bool
	LocalAutoSpawnApproved bool
}

// TakeoverToken is generated by Mindrail with CSPRNG. An idempotent host must
// retain this token for idempotent retries and must never invent takeover
// credentials. A recovery query carries an empty token; the host returns the
// retained token or ErrHostPreparationMissing when the side effect never ran.
type BootstrapEnvelope struct{ IntentID, TaskID, CheckpointID, TakeoverToken string }
type PreparedSuccessor struct {
	OperationID   string
	TakeoverToken string
}

// HostBridge is implemented by a client-specific, host-local adapter. Generic
// MCP wiring must use an unavailable bridge instead of overstating capability.
type HostBridge interface {
	Capabilities(context.Context) HostCapabilities
	PrepareSuccessor(context.Context, BootstrapEnvelope) (PreparedSuccessor, error)
	ActivateSuccessor(context.Context, string) error
}

type UnavailableHost struct{}

func (UnavailableHost) Capabilities(context.Context) HostCapabilities { return HostCapabilities{} }
func (UnavailableHost) PrepareSuccessor(context.Context, BootstrapEnvelope) (PreparedSuccessor, error) {
	return PreparedSuccessor{}, ErrHostCapabilityUnavailable
}
func (UnavailableHost) ActivateSuccessor(context.Context, string) error {
	return ErrHostCapabilityUnavailable
}
